export type ToolCategory =
  | "all"
  | "organize"
  | "optimize"
  | "convert-to"
  | "convert-from"
  | "edit"
  | "security"
  | "ai";

export interface Tool {
  slug: string;
  name: string;
  shortName: string;
  description: string;
  longDescription: string;
  category: ToolCategory;
  iconBg: string;
  iconColor: string;
  accept: string;
  acceptLabel: string;
  badge?: string;
  keywords: string[];
}

export const CATEGORIES: { id: ToolCategory; label: string }[] = [
  { id: "all",          label: "All Tools" },
  { id: "organize",     label: "Organize PDF" },
  { id: "optimize",     label: "Optimize PDF" },
  { id: "convert-to",   label: "Convert to PDF" },
  { id: "convert-from", label: "Convert from PDF" },
  { id: "edit",         label: "Edit PDF" },
  { id: "security",     label: "PDF Security" },
  { id: "ai",           label: "AI Tools" },
];

export const TOOLS: Tool[] = [
  // Organize
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    shortName: "Merge PDF",
    description: "Combine PDFs in the order you want with the easiest PDF merger available.",
    longDescription: "Select multiple PDF files and merge them in seconds. Reorder documents before merging and create a perfectly ordered combined PDF.",
    category: "organize",
    iconBg: "#FEE2E2",
    iconColor: "#DC2626",
    accept: ".pdf",
    acceptLabel: "PDF files",
    keywords: ["merge pdf", "combine pdf", "join pdf", "pdf merger online", "free pdf merge"],
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    shortName: "Split PDF",
    description: "Separate one page or a whole set for easy conversion into independent PDF files.",
    longDescription: "Split a PDF into multiple documents, or extract just the pages you need. Choose to split by page range or extract individual pages.",
    category: "organize",
    iconBg: "#FEE2E2",
    iconColor: "#DC2626",
    accept: ".pdf",
    acceptLabel: "PDF file",
    keywords: ["split pdf", "divide pdf", "extract pages pdf", "pdf splitter online"],
  },
  {
    slug: "remove-pages",
    name: "Remove Pages",
    shortName: "Remove Pages",
    description: "Remove unwanted pages from your PDF file with just a few clicks.",
    longDescription: "Select and delete specific pages from your PDF. Preview all pages and choose which ones to remove. Get a clean PDF without the pages you don't need.",
    category: "organize",
    iconBg: "#FEE2E2",
    iconColor: "#DC2626",
    accept: ".pdf",
    acceptLabel: "PDF file",
    keywords: ["remove pages from pdf", "delete pdf pages", "pdf page remover"],
  },
  {
    slug: "extract-pages",
    name: "Extract Pages",
    shortName: "Extract Pages",
    description: "Extract specific pages from a PDF and save them as a new document.",
    longDescription: "Select the exact pages you want to keep and extract them into a brand new PDF file. Perfect for pulling out specific sections from large documents.",
    category: "organize",
    iconBg: "#FEE2E2",
    iconColor: "#DC2626",
    accept: ".pdf",
    acceptLabel: "PDF file",
    keywords: ["extract pages from pdf", "pull pages pdf", "pdf page extractor"],
  },
  {
    slug: "organize-pdf",
    name: "Organize PDF",
    shortName: "Organize PDF",
    description: "Reorder, rotate, and arrange PDF pages exactly the way you want.",
    longDescription: "Visually rearrange pages by dragging and dropping them. Rotate individual pages, delete unwanted ones, and create the perfect document layout.",
    category: "organize",
    iconBg: "#FEE2E2",
    iconColor: "#DC2626",
    accept: ".pdf",
    acceptLabel: "PDF file",
    keywords: ["organize pdf pages", "reorder pdf", "arrange pdf pages", "pdf page organizer"],
  },

  // Optimize
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    shortName: "Compress PDF",
    description: "Reduce file size while optimizing for maximal PDF quality.",
    longDescription: "Drastically reduce the size of your PDF without losing quality. Choose from extreme, recommended, or less compression to fit your needs.",
    category: "optimize",
    iconBg: "#DBEAFE",
    iconColor: "#2563EB",
    accept: ".pdf",
    acceptLabel: "PDF file",
    keywords: ["compress pdf", "reduce pdf size", "pdf compressor online", "shrink pdf file"],
  },
  {
    slug: "repair-pdf",
    name: "Repair PDF",
    shortName: "Repair PDF",
    description: "Repair a damaged PDF and recover data from corrupt PDF files.",
    longDescription: "Upload your broken or corrupt PDF file and our tool will attempt to repair it and recover as much data as possible. Get your document back in working order.",
    category: "optimize",
    iconBg: "#DBEAFE",
    iconColor: "#2563EB",
    accept: ".pdf",
    acceptLabel: "PDF file",
    keywords: ["repair pdf", "fix corrupt pdf", "pdf repair tool", "recover pdf data"],
  },
  {
    slug: "ocr-pdf",
    name: "OCR PDF",
    shortName: "OCR PDF",
    description: "Easily convert scanned PDF into searchable and selectable documents.",
    longDescription: "Apply Optical Character Recognition to scanned documents or image PDFs. Make text searchable, selectable, and editable in seconds.",
    category: "optimize",
    iconBg: "#DBEAFE",
    iconColor: "#2563EB",
    accept: ".pdf",
    acceptLabel: "PDF file",
    keywords: ["ocr pdf", "searchable pdf", "scanned pdf to text", "pdf ocr online free"],
  },

  // Convert to PDF
  {
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    shortName: "JPG to PDF",
    description: "Convert JPG images to PDF in seconds. Easily adjust orientation and margins.",
    longDescription: "Turn one or multiple JPG images into a single PDF file. Control page size, orientation, and image margins before generating your PDF.",
    category: "convert-to",
    iconBg: "#EDE9FE",
    iconColor: "#7C3AED",
    accept: ".jpg,.jpeg,.png,.webp,.gif,.bmp",
    acceptLabel: "image files",
    keywords: ["jpg to pdf", "image to pdf", "convert jpg to pdf online", "jpeg to pdf free"],
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    shortName: "Word to PDF",
    description: "Make DOC and DOCX files easy to read by converting them to PDF.",
    longDescription: "Convert Word documents to PDF format with perfect layout preservation. Your formatting, fonts, tables, and images will look exactly as they do in Word.",
    category: "convert-to",
    iconBg: "#EDE9FE",
    iconColor: "#7C3AED",
    accept: ".doc,.docx",
    acceptLabel: "Word files",
    keywords: ["word to pdf", "doc to pdf", "docx to pdf converter online", "convert word free"],
  },
  {
    slug: "powerpoint-to-pdf",
    name: "PowerPoint to PDF",
    shortName: "PPT to PDF",
    description: "Make PPT and PPTX slideshows easy to view by converting them to PDF.",
    longDescription: "Convert PowerPoint presentations to PDF with all slides, animations, and formatting preserved. Share your presentations with anyone, on any device.",
    category: "convert-to",
    iconBg: "#EDE9FE",
    iconColor: "#7C3AED",
    accept: ".ppt,.pptx",
    acceptLabel: "PowerPoint files",
    keywords: ["ppt to pdf", "powerpoint to pdf", "pptx to pdf converter online"],
  },
  {
    slug: "excel-to-pdf",
    name: "Excel to PDF",
    shortName: "Excel to PDF",
    description: "Make EXCEL spreadsheets easy to read by converting them to PDF.",
    longDescription: "Convert Excel spreadsheets to PDF with all data, charts, and formatting intact. Perfect for sharing reports and financial data without sharing the editable file.",
    category: "convert-to",
    iconBg: "#EDE9FE",
    iconColor: "#7C3AED",
    accept: ".xls,.xlsx,.csv",
    acceptLabel: "Excel files",
    keywords: ["excel to pdf", "xlsx to pdf", "convert spreadsheet to pdf", "xls to pdf online"],
  },
  {
    slug: "html-to-pdf",
    name: "HTML to PDF",
    shortName: "HTML to PDF",
    description: "Convert webpages in HTML to PDF with a single click.",
    longDescription: "Enter a URL or paste HTML code and convert it to a high-quality PDF. Preserve the layout, styles, and images of any webpage.",
    category: "convert-to",
    iconBg: "#EDE9FE",
    iconColor: "#7C3AED",
    accept: ".html,.htm",
    acceptLabel: "HTML files or URLs",
    keywords: ["html to pdf", "webpage to pdf", "url to pdf converter online"],
  },

  // Convert from PDF
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    shortName: "PDF to JPG",
    description: "Convert each PDF page into a JPG or extract all images contained in a PDF.",
    longDescription: "Convert every page of your PDF into high-quality JPG images, or extract just the embedded images. Control image quality and resolution.",
    category: "convert-from",
    iconBg: "#DCFCE7",
    iconColor: "#16A34A",
    accept: ".pdf",
    acceptLabel: "PDF file",
    keywords: ["pdf to jpg", "pdf to image", "convert pdf to jpeg online free", "pdf pages to jpg"],
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    shortName: "PDF to Word",
    description: "Easily convert your PDF files into easy to edit DOC and DOCX documents.",
    longDescription: "The converted Word document is almost 100% accurate. Your text, images, tables, and formatting are preserved in an editable Word document.",
    category: "convert-from",
    iconBg: "#DCFCE7",
    iconColor: "#16A34A",
    accept: ".pdf",
    acceptLabel: "PDF file",
    keywords: ["pdf to word", "pdf to docx", "convert pdf to word free online", "pdf to editable word"],
  },
  {
    slug: "pdf-to-powerpoint",
    name: "PDF to PowerPoint",
    shortName: "PDF to PPT",
    description: "Turn your PDF files into easy to edit PPT and PPTX slideshows.",
    longDescription: "Transform PDF documents into editable PowerPoint presentations. Each page becomes a slide with text and images in their original positions.",
    category: "convert-from",
    iconBg: "#DCFCE7",
    iconColor: "#16A34A",
    accept: ".pdf",
    acceptLabel: "PDF file",
    keywords: ["pdf to powerpoint", "pdf to pptx", "convert pdf to ppt online free"],
  },
  {
    slug: "pdf-to-excel",
    name: "PDF to Excel",
    shortName: "PDF to Excel",
    description: "Pull data straight from PDFs into Excel spreadsheets in a few short seconds.",
    longDescription: "Intelligently extract tables and data from PDF files and convert them into Excel spreadsheets. Edit your data with full Excel functionality.",
    category: "convert-from",
    iconBg: "#DCFCE7",
    iconColor: "#16A34A",
    accept: ".pdf",
    acceptLabel: "PDF file",
    keywords: ["pdf to excel", "pdf to xlsx", "convert pdf table to excel online"],
  },

  // Edit PDF
  {
    slug: "rotate-pdf",
    name: "Rotate PDF",
    shortName: "Rotate PDF",
    description: "Rotate your PDFs the way you need them. You can even rotate multiple PDFs at once.",
    longDescription: "Fix the orientation of your PDF pages by rotating them 90, 180, or 270 degrees. Apply rotation to individual pages or the entire document at once.",
    category: "edit",
    iconBg: "#FEF3C7",
    iconColor: "#D97706",
    accept: ".pdf",
    acceptLabel: "PDF file",
    keywords: ["rotate pdf", "pdf rotation online", "fix pdf orientation", "rotate pdf pages free"],
  },
  {
    slug: "add-page-numbers",
    name: "Page Numbers",
    shortName: "Page Numbers",
    description: "Add page numbers into PDFs with ease. Choose your positions, dimensions, typography.",
    longDescription: "Add professional page numbers to your PDF document. Customize the position, font, size, and starting number. Apply to all pages or a custom range.",
    category: "edit",
    iconBg: "#FEF3C7",
    iconColor: "#D97706",
    accept: ".pdf",
    acceptLabel: "PDF file",
    keywords: ["add page numbers to pdf", "pdf page numbering", "number pdf pages online"],
  },
  {
    slug: "add-watermark",
    name: "Watermark PDF",
    shortName: "Watermark",
    description: "Stamp an image or text over your PDF in seconds. Choose the typography, transparency and position.",
    longDescription: "Add a text or image watermark to your PDF pages. Customize the font, color, size, rotation, opacity, and position of the watermark.",
    category: "edit",
    iconBg: "#FEF3C7",
    iconColor: "#D97706",
    accept: ".pdf",
    acceptLabel: "PDF file",
    keywords: ["add watermark to pdf", "pdf watermark online", "stamp pdf text", "watermark pdf free"],
  },
  {
    slug: "crop-pdf",
    name: "Crop PDF",
    shortName: "Crop PDF",
    description: "Crop margins of PDF documents or select specific areas, then apply to one or all pages.",
    longDescription: "Precisely crop your PDF by selecting a region visually or entering exact margin values. Remove white borders or focus on specific content areas.",
    category: "edit",
    iconBg: "#FEF3C7",
    iconColor: "#D97706",
    accept: ".pdf",
    acceptLabel: "PDF file",
    keywords: ["crop pdf", "trim pdf margins", "cut pdf pages online", "pdf cropper free"],
  },
  {
    slug: "edit-pdf",
    name: "Edit PDF",
    shortName: "Edit PDF",
    description: "Add text, images, shapes or freehand annotations to a PDF document.",
    longDescription: "Open any PDF and add text, images, shapes, highlights, and freehand drawings. Edit the size, font, and color of added content. A full PDF editor in your browser.",
    category: "edit",
    iconBg: "#FEF3C7",
    iconColor: "#D97706",
    accept: ".pdf",
    acceptLabel: "PDF file",
    keywords: ["edit pdf online", "pdf editor free", "add text to pdf", "annotate pdf online"],
  },

  // Security
  {
    slug: "unlock-pdf",
    name: "Unlock PDF",
    shortName: "Unlock PDF",
    description: "Remove PDF password security, giving you the freedom to use your PDFs as you want.",
    longDescription: "Remove the password protection from your PDF file. Once unlocked, you can open, edit, and share your PDF without entering a password every time.",
    category: "security",
    iconBg: "#EEF2FF",
    iconColor: "#4F46E5",
    accept: ".pdf",
    acceptLabel: "PDF file",
    keywords: ["unlock pdf", "remove pdf password", "pdf unlocker online", "decrypt pdf free"],
  },
  {
    slug: "protect-pdf",
    name: "Protect PDF",
    shortName: "Protect PDF",
    description: "Protect PDF files with a password. Encrypt PDF documents to prevent unauthorized access.",
    longDescription: "Add a strong password to your PDF to control who can open it. Set separate permissions to prevent printing, copying, or editing of the document.",
    category: "security",
    iconBg: "#EEF2FF",
    iconColor: "#4F46E5",
    accept: ".pdf",
    acceptLabel: "PDF file",
    keywords: ["protect pdf", "add password to pdf", "encrypt pdf online", "secure pdf free"],
  },
  {
    slug: "sign-pdf",
    name: "Sign PDF",
    shortName: "Sign PDF",
    description: "Sign yourself or request electronic signatures from others.",
    longDescription: "Electronically sign PDF documents by drawing, typing, or uploading your signature. Request signatures from others and track the signing process.",
    category: "security",
    iconBg: "#EEF2FF",
    iconColor: "#4F46E5",
    accept: ".pdf",
    acceptLabel: "PDF file",
    keywords: ["sign pdf online", "electronic signature pdf", "e-sign pdf free", "digital signature pdf"],
  },
  {
    slug: "redact-pdf",
    name: "Redact PDF",
    shortName: "Redact PDF",
    description: "Redact text and graphics to permanently remove sensitive information from a PDF.",
    longDescription: "Permanently black out sensitive information in your PDF. Unlike just covering text with a rectangle, redaction removes the underlying data completely.",
    category: "security",
    iconBg: "#EEF2FF",
    iconColor: "#4F46E5",
    accept: ".pdf",
    acceptLabel: "PDF file",
    keywords: ["redact pdf", "black out pdf text", "remove sensitive info pdf", "pdf redaction tool"],
  },
  {
    slug: "compare-pdf",
    name: "Compare PDF",
    shortName: "Compare PDF",
    description: "Show a side-by-side document comparison and easily spot changes between different file versions.",
    longDescription: "Upload two versions of a PDF and instantly see exactly what changed between them. Additions, deletions, and modifications are clearly highlighted.",
    category: "security",
    iconBg: "#EEF2FF",
    iconColor: "#4F46E5",
    accept: ".pdf",
    acceptLabel: "PDF files",
    keywords: ["compare pdf files", "pdf diff tool", "find differences in pdf", "pdf comparison online"],
  },

  // AI
  {
    slug: "ai-summarizer",
    name: "AI Summarizer",
    shortName: "AI Summary",
    description: "Quickly generate concise summaries from PDF documents using AI.",
    longDescription: "Upload any PDF and get an instant AI-powered summary. Our AI reads through the entire document and extracts the key points, saving you hours of reading.",
    category: "ai",
    iconBg: "#ECFEFF",
    iconColor: "#0891B2",
    accept: ".pdf",
    acceptLabel: "PDF file",
    badge: "New",
    keywords: ["summarize pdf", "pdf summary ai", "ai pdf summarizer free", "pdf to summary"],
  },
  {
    slug: "translate-pdf",
    name: "Translate PDF",
    shortName: "Translate PDF",
    description: "Easily translate PDF files powered by AI. Keep fonts, layout, and formatting perfectly intact.",
    longDescription: "Translate your PDF into 50+ languages using cutting-edge AI. The translated document preserves the original layout, fonts, and design with remarkable accuracy.",
    category: "ai",
    iconBg: "#ECFEFF",
    iconColor: "#0891B2",
    accept: ".pdf",
    acceptLabel: "PDF file",
    badge: "New",
    keywords: ["translate pdf", "pdf translation online", "ai pdf translator free", "pdf language converter"],
  },
];

export function getToolBySlug(slug: string): Tool | undefined {
  return TOOLS.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: ToolCategory): Tool[] {
  if (category === "all") return TOOLS;
  return TOOLS.filter((t) => t.category === category);
}
